name: CI

on:
  push:
    branches:
      - '*'
    tags:
      - 'v*'
  pull_request:
    branches:
      - main

jobs:
  test:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v4
      with:
         submodules: 'recursive'
    - name: Set up MS tools
      if: matrix.os == 'windows-latest'
      uses: ilammy/msvc-dev-cmd@v1
    - uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: '8'
        cache: 'maven'
    - run: mvn --batch-mode --update-snapshots package
    - name: Upload JAR
      uses: actions/upload-artifact@v4
      with:
        name: "package-${{ matrix.os }}"
        if-no-files-found: error
        path: target/jfasttext*.jar
