name: CI

on:
  push:
    branches:
      - '*'
    tags:
      - 'v*'
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
         submodules: 'recursive'
    - uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: '8'
        cache: 'maven'
    - run: mvn --batch-mode --update-snapshots package
    - name: Upload JAR
      uses: actions/upload-artifact@v4
      with:
        name: package
        if-no-files-found: error
        path: target/jfasttext*.jar
